#!/usr/bin/env python3
"""Write a read-only Stage 0 PR cleanup export handoff script.

This helper prepares the exact `gh pr view` export commands needed by
`amr_beta_pr_cleanup_status.py`. It does not call GitHub, does not close or
merge pull requests, does not push, and does not create benchmark evidence.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shlex
import sys
from pathlib import Path

import amr_beta_pr_cleanup_status as pr_cleanup

SCHEMA = "amr_beta_pr_cleanup_export_plan.v1"
GH_PR_VIEW_FIELDS = [
    "number",
    "state",
    "title",
    "url",
    "closed",
    "mergedAt",
    "closedAt",
    "headRefName",
    "baseRefName",
]
DEFAULT_CLAIM_FILES = [
    "README.md",
    "README.ko.md",
    "docs/AMR_BETA_HUMAN_INPUT_PACKET.md",
]
BLOCKED_FLAGS = {
    "design_partner_beta_candidate_ready": 0,
    "release_ready": 0,
    "public_comparison_claim_ready": 0,
    "real_model_execution_ready": 0,
}


def sha256_file(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def command_line(parts: list[object]) -> str:
    return " ".join(shlex.quote(str(part)) for part in parts)


def output_exists_errors(paths: dict[str, Path], overwrite: bool) -> list[str]:
    errors: list[str] = []
    seen: dict[Path, str] = {}
    for name, path in paths.items():
        resolved = path.resolve()
        if pr_cleanup.is_forbidden_env_path(resolved):
            errors.append(f"{name} must not be .env-like")
        if resolved in seen:
            errors.append(f"{name} must not reuse {seen[resolved]} path: {resolved}")
        seen[resolved] = name
        if name == "out_sh" and path.exists() and not overwrite:
            errors.append(f"out_sh already exists; use --overwrite: {path}")
    return errors


def claim_file_errors(paths: list[Path]) -> list[str]:
    errors: list[str] = []
    seen: set[Path] = set()
    for path in paths:
        resolved = path.resolve()
        if pr_cleanup.is_forbidden_env_path(resolved):
            errors.append(f"claim_file must not be .env-like: {resolved}")
        if resolved in seen:
            errors.append(f"duplicate claim_file: {resolved}")
        seen.add(resolved)
        if not resolved.is_file():
            errors.append(f"claim_file must exist: {resolved}")
    return errors


def pr_number_errors(checklist_pr: int, stale_prs: list[int]) -> list[str]:
    errors: list[str] = []
    if checklist_pr <= 0:
        errors.append("checklist_pr must be positive")
    seen: set[int] = {checklist_pr}
    for number in stale_prs:
        if number <= 0:
            errors.append("stale_pr values must be positive")
        if number in seen:
            errors.append(f"duplicate PR number in export plan: {number}")
        seen.add(number)
    return errors


def script_text(
    *,
    checklist_pr: int,
    stale_prs: list[int],
    claim_files: list[Path],
    pr_state_out: Path,
    status_json_out: Path,
    status_md_out: Path,
) -> str:
    fields = ",".join(GH_PR_VIEW_FIELDS)
    export_prs = [checklist_pr, *stale_prs]
    directories = sorted(
        {pr_state_out.parent.resolve(), status_json_out.parent.resolve(), status_md_out.parent.resolve()},
        key=str,
    )
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by scripts/amr_beta_pr_cleanup_export_plan.py.",
        "# This script exports PR state with gh pr view and runs the local",
        "# Stage 0 claim-freeze validator. It performs no GitHub mutations.",
        "",
    ]
    for directory in directories:
        lines.append(command_line(["mkdir", "-p", directory]))
    lines.extend(
        [
            command_line([":"]) + " > " + shlex.quote(str(pr_state_out)),
            "",
        ]
    )
    for number in export_prs:
        lines.append(
            command_line(["gh", "pr", "view", number, "--json", fields])
            + " >> "
            + shlex.quote(str(pr_state_out))
        )
    validate_parts: list[object] = [
        "python3",
        "scripts/amr_beta_pr_cleanup_status.py",
        "--pr-state",
        pr_state_out,
        "--checklist-pr",
        checklist_pr,
    ]
    for number in stale_prs:
        validate_parts.extend(["--stale-pr", number])
    for claim_file in claim_files:
        validate_parts.extend(["--claim-file", claim_file])
    validate_parts.extend(
        [
            "--require-claim-scan",
            "--out-json",
            status_json_out,
            "--out-md",
            status_md_out,
            "--overwrite",
        ]
    )
    lines.extend(["", command_line(validate_parts)])
    return "\n".join(lines).rstrip() + "\n"


def build_payload(
    *,
    out_sh: Path,
    pr_state_out: Path,
    status_json_out: Path,
    status_md_out: Path,
    checklist_pr: int,
    stale_prs: list[int],
    claim_files: list[Path],
    script_sha256: str,
    errors: list[str],
) -> dict[str, object]:
    return {
        "schema": SCHEMA,
        "ready_for_pr_cleanup_export_handoff": int(not errors),
        "out_sh": str(out_sh),
        "out_sh_sha256": script_sha256,
        "pr_state_out": str(pr_state_out),
        "status_json_out": str(status_json_out),
        "status_md_out": str(status_md_out),
        "checklist_pr": checklist_pr,
        "stale_prs": stale_prs,
        "export_pr_count": 1 + len(stale_prs),
        "gh_pr_view_fields": GH_PR_VIEW_FIELDS,
        "claim_files": [str(path) for path in claim_files],
        "claim_file_count": len(claim_files),
        "writes_export_script": int(bool(script_sha256)),
        "runs_github_query": 0,
        "runs_github_mutation": 0,
        "runs_git_push": 0,
        "closes_pull_requests": 0,
        "merges_pull_requests": 0,
        "creates_benchmark_evidence": 0,
        "generated_script_runs_github_query": 1,
        "generated_script_runs_github_mutation": 0,
        **BLOCKED_FLAGS,
        "errors": errors,
    }


def write_script(path: Path, text: str, overwrite: bool) -> str:
    if pr_cleanup.is_forbidden_env_path(path):
        raise ValueError("refusing .env-like shell output path")
    if path.exists() and not overwrite:
        raise ValueError(f"out_sh already exists; use --overwrite: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    path.chmod(0o755)
    return sha256_file(path)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-sh", required=True, help="Shell handoff script to write.")
    parser.add_argument("--pr-state-out", default="results/amr_beta_pr_cleanup_state.jsonl")
    parser.add_argument("--status-json-out", default="results/amr_beta_pr_cleanup_status.json")
    parser.add_argument("--status-md-out", default="results/amr_beta_pr_cleanup_status.md")
    parser.add_argument("--checklist-pr", type=int, default=pr_cleanup.DEFAULT_CHECKLIST_PR)
    parser.add_argument("--stale-pr", action="append", type=int, default=[])
    parser.add_argument("--claim-file", action="append", default=[])
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--json", action="store_true")
    return parser


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)
    out_sh = Path(args.out_sh).expanduser().resolve()
    pr_state_out = Path(args.pr_state_out).expanduser().resolve()
    status_json_out = Path(args.status_json_out).expanduser().resolve()
    status_md_out = Path(args.status_md_out).expanduser().resolve()
    stale_prs = args.stale_pr or pr_cleanup.DEFAULT_STALE_PRS
    claim_files = [
        Path(raw).expanduser().resolve()
        for raw in (args.claim_file or DEFAULT_CLAIM_FILES)
    ]
    output_paths = {
        "out_sh": out_sh,
        "pr_state_out": pr_state_out,
        "status_json_out": status_json_out,
        "status_md_out": status_md_out,
    }
    errors = [
        *output_exists_errors(output_paths, args.overwrite),
        *claim_file_errors(claim_files),
        *pr_number_errors(args.checklist_pr, stale_prs),
    ]
    script_sha = ""
    if not errors:
        try:
            script_sha = write_script(
                out_sh,
                script_text(
                    checklist_pr=args.checklist_pr,
                    stale_prs=stale_prs,
                    claim_files=claim_files,
                    pr_state_out=pr_state_out,
                    status_json_out=status_json_out,
                    status_md_out=status_md_out,
                ),
                args.overwrite,
            )
        except Exception as exc:
            errors.append(str(exc))
    payload = build_payload(
        out_sh=out_sh,
        pr_state_out=pr_state_out,
        status_json_out=status_json_out,
        status_md_out=status_md_out,
        checklist_pr=args.checklist_pr,
        stale_prs=stale_prs,
        claim_files=claim_files,
        script_sha256=script_sha,
        errors=errors,
    )
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if not args.json:
        print(f"pr_cleanup_export_plan: ok out_sh={out_sh}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
